name = "Appendices"
version = "0.1.0"
defaultTargets = ["Appendices", "MainText"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[lean_lib]]
name = "Appendices"

[[lean_lib]]
name = "MainText"
